include: package:lint/package.yaml

linter:
  rules:
    - prefer_double_quotes
    - avoid_final_parameters
    - parameter_assignments
    - avoid_print
    - prefer_final_locals
    - prefer_final_in_for_each
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - unawaited_futures
    - unnecessary_lambdas
    - prefer_int_literals

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    todo: info
