name: podprefs
description: Simple low-boilerplate preferences using Riverpod and Shared Preferences.
repository: https://github.com/petlyh/podprefs
issue_tracker: https://github.com/petlyh/podprefs/issues
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.5.0
  shared_preferences: ^2.3.0

dev_dependencies:
  lint: ^2.3.0
